name: Update Lambda Layer and Function try 1

on:
  push:
    branches:
      - aqil-hana

jobs:
  update-lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Lambda Layer ZIP
        id: 'create_zip'
        run: |
          # Create a new ZIP file containing the updated Lambda Layer contents
          # You can customize this step according to your project structure
          
          sudo apt-get update
          sudo apt-get install python3 python3-pip zip -y
          rm -rf python
          mkdir python
          pip3 install -r requirements.txt -t python/
          zip -r XlsWriter.zip python/
          
      - name: 'Create Artifacts'
        id: 'create_artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: latest-layer
          path: ${{ github.workspace }}/${{ steps.create_zip.outputs.package_name }}

      - name: Upload Lambda Layer ZIP to S3
        run: |
          aws s3 cp XlsWriter.zip s3://bucket-test-777/hana-test/
        env:
          TF_VAR_bucket_name: ${{ secrets.TF_VAR_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1  # Replace with your desired AWS region

      - name: Run Terraform
        run: |
          cd layer
          terraform init
          terraform apply -auto-approve ; terraform apply -lock=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1  # Replace with your desired AWS region

      # - name: Update Lambda
      #   id: 'update_latest'
      #   run: |
      #     latest_version=$(aws lambda list-layer-versions --layer-name hanalayer --query 'max_by(LayerVersions, &Version).Version' --output text)
      #     echo "Latest Layer Version: $latest_version"
      #     aws lambda update-function-configuration --function-name hanalambda --layers arn:aws:lambda:ap-southeast-1:${{ secrets.AWS_ACCOUNT_ID }}:layer:hanalayer:$latest_version
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ap-southeast-1  # Replace with your desired AWS region
